---
title: "20181107"
output: html_notebook
---

```{r}
library(stringr)
library(lubridate)
`民國年月`<-c("099/01","099/02","099/03")

# 1
str_c("1",`民國年月`,"/01")->`民國年月`

# 2
lubridate::ymd(`民國年月`) -> `民國年月`

# 3
`民國年月` + years(911)
```

```{r}
library(readr)
collegeData <- read_csv("https://quality.data.gov.tw/dq_download_csv.php?nid=6231&md5_url=dda8fca407131483c1d8cbf3d61cf793")

```

```{r}
library(dplyr)
mutate(
  collegeData,
  學校代碼=as.factor(學校代碼),
  學校名稱=as.factor(學校名稱)
  ) -> collegeData2

```
```{r}

```

# 舊寫法
```{r}
collegeData$學校代碼<-as.factor(collegeData$學校代碼)
collegeData$學校名稱<-as.factor(collegeData$學校名稱)
collegeData -> collegeData2
```

```{r}
collegeData$`日間∕進修別`<-as.factor(collegeData$`日間∕進修別`)
collegeData$等級別<-as.factor(collegeData$等級別)
 collegeData$一年級男生<-as.numeric(collegeData$一年級男生)
collegeData$一年級女生<-as.numeric(collegeData$一年級女生)
 collegeData -> collegeData2
```
 # mutate寫法

```{r}
library(dplyr)
mutate(collegeData,
       `日間∕進修別`=as.factor(`日間∕進修別`),
       等級別=as.factor(等級別),
       一年級男生=as.numeric(一年級男生),
       一年級女生=as.numeric(一年級女生)
       ) ->
  collegeData2
```
 # pipe
```{r}
library(dplyr)
collegeData %>%
mutate(
       `日間∕進修別`=as.factor(`日間∕進修別`),
       等級別=as.factor(等級別),
       一年級男生=as.numeric(一年級男生),
       一年級女生=as.numeric(一年級女生)
       ) ->
  collegeData2
```


```{r}
library(stringr)
collegeData %>%
  mutate(
    一年級男生=str_replace(一年級男生,",",""),
    一年級女生=str_replace(一年級女生,",","")
  ) %>%
  mutate(
    二年級男生=str_replace(二年級男生,",","")
  ) %>%
   mutate(
    一年級男生=as.numeric(一年級男生),
    一年級女生=as.numeric(一年級女生)
  ) -> collegeData3
```
```

